DROP TABLE IF EXISTS property;
DROP TABLE IF EXISTS inquiry;

CREATE TABLE property (
	propertyId INT UNSIGNED AUTO_INCREMENT NOT NULL,

);
CREATE TABLE inquiry (
	buyerEmail INT UNSIGNED AUTO_INCREMENT NOT NULL,
)
